
require 'base.plugin_install'
require 'base.config'
require 'base.themes'
require 'base.mapping'
--
require 'plugins.bufferline'
require 'plugins.lualine'
require 'plugins.nvimtree'
require 'plugins.treesitter'
require 'plugins.lspinstaller'
require 'plugins.lspconfig'
require 'plugins.luasnip'
require 'plugins.comment'
require 'plugins.indentblackline'
require 'plugins.telescope'
require 'plugins.toggleterm'

require 'mapping.base'
require 'mapping.bufferline'
require 'mapping.delete_arrow'
require 'mapping.nvimtree'
require 'mapping.luasnip'
require 'mapping.tagbar'
require 'mapping.telescope'

