vim.keymap.set("n", "gD", vim.lsp.buf.declaration, { silent = true })
vim.keymap.set("n", "gd", vim.lsp.buf.definition, { silent = true })
vim.keymap.set("n", "gr", vim.lsp.buf.rename, { silent = true })
vim.keymap.set("n", "go", vim.lsp.buf.hover, { silent = true })
vim.keymap.set("n", "gi", vim.lsp.buf.implementation, { silent = true })
